### ISSUE TITLE
gitbook.com links are all broken

### ISSUE THREAD

**Issue by jessep** [GitbookIO/nuts#106]
It looks like nuts.gitbook.com doesn't exist, all the links from the README are leading to server not found errors.

**Comment by alexcroox** [comment]
Is this why the "deploy to Heroku" button doesn't do anything on Heroku for me?

**Comment by jessep** [comment]
Seems to be working now

**Comment by Zamiell** [comment]
Deploy to Heroku button still fails for me... can anyone else confirm?
