### ISSUE TITLE
A little more documentation on the GitHub webhook setup

### ISSUE THREAD

**Issue by bluedaniel** [GitbookIO/nuts#11]
I had a little trouble with getting webhooks working at first, the only response being `{"error":"No X-Hub-Signature found on request"}`.

Using the search below I found that the webhook secret has to be set to `"secret"` in order to work. Just pointing it out in case someone else misses it.

https://github.com/GitbookIO/nuts/search?utf8=%E2%9C%93&q=webhook

Thanks for all your work on nuts!

**Comment by SamyPesse** [comment]
You can change this secret using `GITHUB_SECRET`

**Comment by Gan-Jason** [comment]
thx,u help me a lot

**Comment by almamlaka** [comment]
@SamyPesse GITHUB_SECRET should be change in own server ? or in github ?
