### ISSUE TITLE
What files should I upload for Windows updates?

### ISSUE THREAD

**Issue by matiastucci** [GitbookIO/nuts#135]
I'm using `electron-builder` with `squirrel` as `target`. This is generating a `RELEASES`, `.nupkg` and `setup` file.

My question is: what should I upload to my GitHub release? a `.zip` with all those files?

**Comment by bartkozal** [comment]
You need all of them and not necessarily in a `.zip` package. At least, that's how I make releases and everything works as expected:

![screen shot 2017-03-15 at 17 34 23](https://cloud.githubusercontent.com/assets/127219/23959528/b84f57d6-09a5-11e7-9522-393e76b0fa9b.png)

**Comment by matiastucci** [comment]
I'll try that. Thanks!
