### ISSUE TITLE
auto update requesting "...latest.yml"

### ISSUE THREAD

**Issue by geoffoliver** [GitbookIO/nuts#174]
I followed the instructions [here](https://nuts.gitbook.com/update-osx.html) and the auto updater is requesting something i have _not_ set as the feed URL -- "mac-latest.yml".. or "latest.yml" or whatever platform it is on. What am I doing wrong?

**Comment by geoffoliver** [comment]
Never mind, this shit hasn't had a commit for __THREE FUCKING YEARS__.

**Comment by karahan** [comment]
@plan8studios Question, which alternative did u use? Or did you find a fix for this issue?

**Comment by geoffoliver** [comment]
@karahan I ended up just uploading the files straight to a web server, and configuring the electron-updater thing to grab the files from there. No release server involved. Not great, but it works for now :)

**Comment by karahan** [comment]
oh, thanks for the quick response :). I'll look for alternatives but might end up doing the same.

**Comment by geoffoliver** [comment]
Good luck!
