### ISSUE TITLE
Squirrel.Windows receives unexpected response from RELEASES request, throws Exception 

### ISSUE THREAD

**Issue by rbkreisberg** [GitbookIO/nuts#18]
**edited**

I think this line needs to be removed:
https://github.com/GitbookIO/nuts/blob/master/lib/index.js#L214

Starting with a update check in Squirrel Windows:
https://github.com/Squirrel/Squirrel.Windows/blob/1ed86dbc6f4cf3adb7d111986b28203c5178a27e/src/Update/Program.cs#L240

As the response to a request to /update/:platform/:version, Squirrel.Windows expects to get a list of releases if the response has a success status code.  I believe that the 204 that nuts sends back qualifies as a "Success Code".

https://github.com/Squirrel/Squirrel.Windows/blob/d6f83880ee6ebf068f1f2325c6f97255a237678c/src/Squirrel/UpdateManager.Factory.cs#L70

Squirrel.Windows probably takes the empty result and has tags the release to apply as the latest known version ( as a fallback)

https://github.com/Squirrel/Squirrel.Windows/blob/237cf945e492d1fcad678eb5522fe3565db4960e/src/Squirrel/UpdateInfo.cs#L78

Squirrel then requests the RELEASES file for the latest known version:
https://github.com/Squirrel/Squirrel.Windows/blob/d6f83880ee6ebf068f1f2325c6f97255a237678c/src/Squirrel/UpdateManager.CheckForUpdates.cs#L76

and receives another 204 with no response body:
https://github.com/GitbookIO/nuts/blob/master/lib/index.js#L214

the result is that Squirrel throws an Exception from the empty response:
https://github.com/Squirrel/Squirrel.Windows/blob/d6f83880ee6ebf068f1f2325c6f97255a237678c/src/Squirrel/UpdateManager.CheckForUpdates.cs#L124

**Comment by rbkreisberg** [comment]
Edited the issue.  I did some checking and only the logic relating to the RELEASES file should be changed.

**Comment by SamyPesse** [comment]
Sorry for the late answer, What version of Squirrel.Windows are you using?

We are maybe using an old version, but it's working fine for GitBook Editor.

**Comment by SamyPesse** [comment]
If you know how to solve it, can you make a PR. It'll be easier for me to understand the potential solution.

**Comment by rbkreisberg** [comment]
@SamyPesse sure.  #19 is submmited

**Comment by SamyPesse** [comment]
Fixed by #19
