### ISSUE TITLE
Link to Github-independent cousin: electron-release-server

### ISSUE THREAD

**Issue by ArekSredzki** [GitbookIO/nuts#42]
Initially I tried using nuts, but seeing as my use case of releasing an application internally at Tesla did not deal with Github, I ended up developing the app from scratch. Perhaps it'd be of use to others as well, it'd be great if you could link to it as I have to this :) https://github.com/ArekSredzki/electron-release-server

**Comment by SamyPesse** [comment]
Nuts@3.0.0 can work great with other backends than GitHub (https://github.com/GitbookIO/nuts/tree/master/lib/backends). But good work :beers: 

I'll close this issue, since it's not an active problem (it'll still be accessible for devs from the GitHub search).

**Comment by ArekSredzki** [comment]
@SamyPesse Though that is not completely accurate.
Nuts essentially acts as a proxy, but at some point, if the information is all centralized on one machine anyway, it should be designed and built as an application with that intent in mind

**Comment by SamyPesse** [comment]
@ArekSredzki with version 3.0.0, Nuts doesn't have to act as a proxy, the backend can also redirect the user, it can list versions from a Database, get asset from a private S3, redirect to a public S3, etc
