### ISSUE TITLE
Update returning same version

### ISSUE THREAD

**Issue by burakcan** [GitbookIO/nuts#43]
I have 2 versions of my app and trying to make nuts work but; update requests are returning the same versions. Am i missing something?

<img width="1081" alt="screen shot 2016-03-07 at 10 48 21" src="https://cloud.githubusercontent.com/assets/3121257/13564436/49a89a00-e452-11e5-8ec5-c25168cbd898.png">
<img width="1081" alt="screen shot 2016-03-07 at 10 48 11" src="https://cloud.githubusercontent.com/assets/3121257/13564437/49adbf9e-e452-11e5-89c5-865b9518c4d0.png">

**Comment by SamyPesse** [comment]
The problem maybe come from the `v` in the version, i"m not sure nuts handle this correctly (it can easily be fixed).

**Comment by burakcan** [comment]
@SamyPesse thank you for the quick response. Without `v` :
<img width="1061" alt="screen shot 2016-03-07 at 10 54 53" src="https://cloud.githubusercontent.com/assets/3121257/13564528/15152b5e-e453-11e5-89c4-04266f56f3e1.png">

**Comment by SamyPesse** [comment]
Yes it sounds normal, The update is looking for versions `>=0.5.0-alpha`, `0.5.1-alpha` is not superior to `0.5.0-alpha` (the logic behind this is to prevent users from upgrading to the alpha of another version, when they choose to use the alpha of `0.5.0`), `0.5.1` will be shown as an update.

**Comment by burakcan** [comment]
Got it. Thank you @SamyPesse :100:
