### ISSUE TITLE
URL to releases when using electron-builder

### ISSUE THREAD

**Issue by atietje** [GitbookIO/nuts#57]
I use [electron-builder](https://github.com/electron-userland/electron-builder/) to build installers / updates.

To create delta updates I have to add a URL to `package.json` which points to the existing releases like so:

    "build": {
      "win": {
        "remoteReleases": "https://MY-NUTS.herokuapp.com/update/win32/0.3.5/",
      }
    }

When I use that URL, Heroku logs tell me

    method=GET path="/update/win32/0.3.5/RELEASES […] status 200
    [...]
    downloaded my-app-0.3.5-full.nupkg for version 0.3.5 on channel stable for windows_32

Do I have to bump the version in the URL every time? There seems to be no way to point to `latest`.

See also: electron-userland/electron-builder#294

**Comment by zerojuan** [comment]
What was the resolution to this?

**Comment by joeferraro** [comment]
@atietje what did you wind up doing here?

**Comment by atietje** [comment]
@joeferraro Nothing, actually. I abandoned GitbookIO/nuts and integrated release management into our websites Pimcore installation.
