### ISSUE TITLE
Problem with deploying it on my server

### ISSUE THREAD

**Issue by epezhman** [GitbookIO/nuts#81]
I'm a a newbie and I need a bit help with deploying the app on my server (Debian on DigitalOcean). I deployed on Heroku (The deploy button on documentation page is not working, had to do it manually) and it works fine but when I'm trying to deploy it on my own server I can not get access to it page. I tested it locally and still can not access it through the localhost.
I followed the documentation and set all the variables and when running, it says ´Listening at `Listening at http://:::6000` but I always get the page is not available, should I set something else too? thanks a lot

**Comment by epezhman** [comment]
I had to add the 127.0.0.1 when working with Nginx as proxy server

**Comment by akashnimare** [comment]
@epezhman where did you add 127.0.0.1?

**Comment by epezhman** [comment]
I think, to the docker command, so it runs on some address like http://127.0.0.1:6000. I'm not really sure though, I did that long time ago and I'm not using `nuts` anymore

**Comment by Malnasser** [comment]
@epezhman Can I know where did u add the local address ?
