### ISSUE TITLE
Support for choosing to update from different channels

### ISSUE THREAD

**Issue by mzmousa** [GitbookIO/nuts#86]
Does Nuts support being able to choose which channel I want to update from? For example, I have my app with version `v0.1.0`. If I want to choose between uploading to version `v0.1.1` or `v0.1.2-alpha` (channel depends on tag names), is there a way to do this? like
```
var platform = ...;
var version = ...; // the usual
autoUpdater.setFeedURL('http://.../update/channel/stable/platform/version")
```
or
```
autoUpdater.setFeedURL("http://.../update/channel/alpha/plaform/version")
```
I know [electron-release-server](https://github.com/ArekSredzki/electron-release-server) does this, but I want to stick with Nuts.

**Comment by JPeColCom** [comment]
Hey try our fork for test https://github.com/Coldewey/nuts
I merged this kind of stuff https://github.com/GitbookIO/nuts/issues/20 to get the channel update behavior

**Comment by mzmousa** [comment]
@JPeColCom I just made a fork that supports this (added a simple route for `/channel`). I'll test yours out soon :)

**Comment by jsloyer** [comment]
👍

**Comment by mzmousa** [comment]
@JPeColCom I got around to trying your fork, it had a bit of stuff missing. Here's my fork - I added new endpoints, and channels are supported by tag name suffixes. I'll submit a PR and see how it goes. I'm using it now for my app if you were interested:

https://github.com/mzmousa/nuts
