### ISSUE TITLE
Version not found: latest

### ISSUE THREAD

**Issue by marekhrabe** [GitbookIO/nuts#94]
I have correctly deployed nuts on heroku and connected it to github repository.

- `/download/0.10.0` works correctly (it's my only released version). it returns zip to download
- `/download` route should give me latest version (0.10.0), instead it says "Version not found: latest"

What should I do to make "latest" work? Github release is marked "latest", so that should not be a problem, right? 

<img width="782" alt="screen shot 2016-07-13 at 13 55 34" src="https://cloud.githubusercontent.com/assets/156676/16802549/888d6a20-4901-11e6-9c78-8d922e2548d5.png">

**Comment by savenko** [comment]
Hello!
I have this error also. What should I do to make "latest" work?

**Comment by benoror** [comment]
I found out that dropping the `/latest` part of the URL works:

http://download.myapp.com/download/latest/osx -> http://download.myapp.com/download/osx

Documentation should be fixed accordingly
